name: Manual release workflow

on:
  release:
    types: [ published ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: '0'

      - name: Set up environment
        run: |
          echo "${{ secrets.GRADLE_PUBLISH_KEY }}" >> ~/.gradle/gradle.properties
          echo "${{ secrets.GRADLE_PUBLISH_SECRET }}" >> ~/.gradle/gradle.properties

      - name: Release tag
        run: |
          git describe --tags --always --first-parent
          git tag

      - name: Setup java
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Run verifications
        run: ./gradlew check

      - name: Upload reports
        uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: Reports
          path: '**/build/test-results/test/*'

      - name: Publish plugin
        run: ./gradlew :publish
